### ISSUE TITLE
 Broken Links in the first "Hinweis" Box

### ISSUE THREAD

**Issue by picturedesk** [AdobeDocs/experience-manager-65.de-DE#1]
Issue in ./help/sites-administering/saml-2-0-authenticationhandler.md

Both links in the first "Hinweis" box are broken.

related to [#348](https://github.com/AdobeDocs/experience-manager-65.en/issues/348)

**Comment by jon34420** [comment]
We are looking into this.

**Comment by yanlicao** [comment]
@picturedesk Thank you for your feedback. This is being reviewed and tracked in G11N-10063

**Comment by yanlicao** [comment]
Dear @picturedesk , just want to provide some updates for you.
The first link is now fixed, but the 2nd one is still under fix.
The 2nd link is being reviewed and tracked in CQDOC-19537. 
Thanks for your patience!

**Comment by yanlicao** [comment]
Dear @picturedesk , please note that this issue should now be resolved.
One of the broken link is fixed, the other one is removed. Please kindly verify.
Close this ticket as fixed.
