### ISSUE TITLE
Please improve the documantation regarding the oak index product issues

### ISSUE THREAD

**Issue by lukaromanov** [AdobeDocs/experience-manager-65.de-DE#2]
Issue in ./help/release-notes/previous/6.5.14.md

We are missing the latest updates regarding the deprecated /oak:index/lucene index and the known issues regarding infinity reindexing loops ("-Doak.indexTracker.autoRefresh=3153600000000").

Based on issues described in the following support ticket:
https://adminconsole.adobe.com/10834B9C5E790BF70A495E96@AdobeOrg/support/support-cases/E-000788108

**Comment by yanlicao** [comment]
@lukaromanov  Thank you for your feedback. This is being reviewed and tracked in <https://github.com/AdobeDocs/experience-manager-65.en/issues/395)>.

**Comment by yanlicao** [comment]
We are using  CQDOC-20071 to track this issue now, thanks for your patience.

**Comment by jonsamhudec** [comment]
This feedback was implemented, and the issue was fixed.
