### ISSUE TITLE
release-notes not correct content

### ISSUE THREAD

**Issue by stejan** [AdobeDocs/experience-manager-65.de-DE#4]
Issue in ./help/release-notes/release-notes.md

Content ist not correct looks like

Content Fragments - GraphQL Query Editor
W
Content Fragments - REST API
W
Core Backend
W
Core Components
I
Campaign integration
A

**Comment by jonsamhudec** [comment]
Thank you for reporting! This looks like a source issue and is being investigated under G11N-16080.

**Comment by jonsamhudec** [comment]
This issue was fixed and no longer appear. Thank you!
